config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds

  resources :scenarios do
    member do
      post 'destroyme'
      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'

      post 'destroy_scenario'
      post 'destroy_cloud'
      post 'destroy_subnet'
      post 'destroy_instance'

      post 'add_cloud'
      post 'add_subnet'
      post 'add_instance'

      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'delete_cloud'
      post 'delete_subnet'
      post 'delete_instance'

      post 'modify'
      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'add_player'
      post 'modify_players'
      post 'delete_player'

      post 'add_student_group'
      post 'remove_student_group'

      post 'get_log'
      post 'get_instance_bash_history'
      post 'boot_status'

      post 'upload'
      post 'save_changes'

    end
  end
  
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get 'instructor', to: 'instructor#index'

  post 'instructor/student_group_new'
  post 'instructor/student_group_assign'
  post 'instructor/student_group_delete'
  post 'instructor/student_group_remove'

  # get 'student_groups', to: 'student_groups#index'
  # post 'student_groups/new'
  # get 'student_groups/destroy'
  post 'student_groups/add_to'
  # get 'student_groups/remove_from'
  # post 'student_groups/add_to'

  get 'student', to: 'student#index'

  get 'admin', to: 'admin#index'
  post 'admin/instructor_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'

  # Insecure, needs to be rewritten
  # get 'scoring/instructor/:scenario', to: 'scoring#instructor'
  # get 'scoring/student/:scenario', to: 'scoring#student'
  # post 'scoring/answer_question/:scenario/:question', to: 'scoring#answer_question'
  # get 'scoring/instructor_student/:scenario/:user', to: 'scoring#instructor_student'
  # post 'scoring/answer_open_question'
  # get 'scoring/answer_dump'
  # get 'documentation', to: 'documentation#index'
  # get 'documentation/scenarios/:id', to: 'documentation#show'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/admin/index.html.haml
%div.modal#modal-create-instructor{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title= "Create Instructor"
      %div.modal-body#modalbody
        = form_tag admin_instructor_create_path(), remote:true, method: :post do 
          %div#email-div
            This will assign a random password for the instructor and will automatically send an email to the instructor with their credentials.
            %p
            = label_tag nil, 'Email:', class: 'control-label'
            = text_field_tag :email, nil, class: 'form-control'
            %span.help-block.inline#email-help
          %div#name-div
            = label_tag nil, 'Name:', class: 'control-label'
            = text_field_tag :name, nil, class: 'form-control'
            %span.help-block.inline#name-help
          %div#organization-div
            = label_tag nil, 'Organization:', class: 'control-label'
            = text_field_tag :organization, nil, class: 'form-control'
            %span.help-block.inline#organization-help
          %p
          = submit_tag 'Create', :class => 'btn btn-default'

      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.modal#modal-student-to-instructor{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title= "Make Student Instructor"
      %div.modal-body#modalbody
        = form_tag admin_student_to_instructor_path(), remote:true, method: :post do 
          %div#email-div
            = label_tag nil, 'Students Email:', class: 'control-label'
            = text_field_tag :email, nil, class: 'form-control'
            %span.help-block.inline#email-help
          %p
          = submit_tag 'Create', :class => 'btn btn-default'

      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h3
        Admin Home

  %div.panel-body
    %h4 Account Information: 
    %div
      %dl
        Name: 
        =@user.name
        %br
        Email:
        =@user.email
        %br
        Password: ********
        %p
        = link_to 'edit', edit_user_registration_path, class: 'btn btn-primary'
        %p
        Last Sign In:
        =@user.last_sign_in_at
        From:
        =@user.last_sign_in_ip 

    %h4 User Information:
    %dl
      = link_to 'Create Instructor', "#modal-create-instructor", :data => {:toggle=>"modal"}, class: 'btn btn-primary', onclick: "$('#modal-create-instructor').find('#email').val(''); $('#modal-create-instructor').find('#name').val(''); $('#modal-create-instructor').find('#organization').val('');"
      = link_to 'Make Student Instructor', "#modal-student-to-instructor", :data => {:toggle=>"modal"}, class: 'btn btn-primary', onclick: "$('#modal-student-to-instructor').find('#email').val('');"

    %div
      %dl
        %h4 Instructors:
        %table#instructors-table
          %tr
            %th Name
            %th Email
            %th Organization
            %th
          - @instructors.each do |instructor|
            %tr{ id: 'instructor-' + instructor.id.to_s }
              %td= instructor.name
              %td= instructor.email
              %td= instructor.organization
              %td= link_to 'delete', admin_instructor_delete_path(:id =>  instructor['id']), remote: true, method: :post

      %dl
        %h4 Students:
        %table#instructors-table
          %tr
            %th Name
            %th Email
            %th Organization
            %th
          - @students.each do |student|
            %tr{ id: 'student-' + student.id.to_s }
              %td= student.name
              %td= student.email
              %td= student.organization
              / # %td= link_to 'delete', admin_instructor_delete_path(:id =>  instructor['id']), remote: true, method: :post

app/views/admin/instructor_create.js.erb
<% if @user.errors.any? %>
    <% if @user.errors[:email].any? %>
        $('#modal-create-instructor').find('#email-div').addClass('has-error');
        $('#modal-create-instructor').find('#email-help').text('<%= @user.errors[:email][0] %>');
    <% end %>
    <% if @user.errors[:name].any? %>
        $('#modal-create-instructor').find('#name-div').addClass('has-error');
        $('#modal-create-instructor').find('#name-help').text('<%= @user.errors[:name][0] %>');
    <% end %>
    <% if @user.errors[:organization].any? %>
        $('#modal-create-instructor').find('#organization-div').addClass('has-error');
        $('#modal-create-instructor').find('#organization-help').text('<%= @user.errors[:organization][0] %>');
    <% end %>
<% else %>
    $('#instructors-table').append("<tr id='instructor-<%= @user.id %>'><td><%= @user.name %></td><td><%= @user.email %></td><td><%= @user.organization %></td><td><a href='/admin/instructor_delete?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true'>delete</a></td></tr>"); 
    $('#modal-create-instructor').modal('toggle');
<% end %>

app/views/admin/instructor_delete.js.erb
$('#instructor-<%= @user.id.to_s %>').remove();

app/views/admin/student_to_instructor.js.erb
<% if @user %>
    <% if @user.errors.any? %>
        <% if @user.errors[:email].any? %>
            $('#modal-student-to-instructor').find('#email-div').addClass('has-error');
            $('#modal-student-to-instructor').find('#email-help').text('<%= @user.errors[:email][0] %>');
        <% end %>
    <% else %>
        $('#instructors-table').append("<tr id='instructor-<%= @user.id %>'><td><%= @user.name %></td><td><%= @user.email %></td><td><%= @user.organization %></td><td><a href='/admin/instructor_delete?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true'>delete</a></td></tr>"); 
        $('#modal-student-to-instructor').modal('toggle');
    <% end %>
<% else %>
    $('#modal-student-to-instructor').find('#email-div').addClass('has-error');
    $('#modal-student-to-instructor').find('#email-help').text('User not found');
<% end %>