config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds

  resources :scenarios do
    member do
      post 'destroyme'
      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'

      post 'destroy_scenario'
      post 'destroy_cloud'
      post 'destroy_subnet'
      post 'destroy_instance'

      post 'add_cloud'
      post 'add_subnet'
      post 'add_instance'

      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'delete_cloud'
      post 'delete_subnet'
      post 'delete_instance'

      post 'modify'
      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'add_player'
      post 'modify_players'
      post 'delete_player'

      post 'add_student_group'
      post 'remove_student_group'

      post 'get_log'
      post 'get_instance_bash_history'
      post 'boot_status'

      post 'upload'
      post 'save_changes'

    end
  end
  
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get 'instructor', to: 'instructor#index'

  post 'instructor/student_group_new'
  post 'instructor/student_group_assign'
  post 'instructor/student_group_delete'
  post 'instructor/student_group_remove'

  # get 'student_groups', to: 'student_groups#index'
  # post 'student_groups/new'
  # get 'student_groups/destroy'
  post 'student_groups/add_to'
  # get 'student_groups/remove_from'
  # post 'student_groups/add_to'

  get 'student', to: 'student#index'

  get 'admin', to: 'admin#index'
  post 'admin/instructor_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'

  # Insecure, needs to be rewritten
  # get 'scoring/instructor/:scenario', to: 'scoring#instructor'
  # get 'scoring/student/:scenario', to: 'scoring#student'
  # post 'scoring/answer_question/:scenario/:question', to: 'scoring#answer_question'
  # get 'scoring/instructor_student/:scenario/:user', to: 'scoring#instructor_student'
  # post 'scoring/answer_open_question'
  # get 'scoring/answer_dump'
  # get 'documentation', to: 'documentation#index'
  # get 'documentation/scenarios/:id', to: 'documentation#show'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :authenticate_admin_or_instructor

  before_action :set_user, only: [:index, :show, :boot_cloud, :delete_player, :get_log, :set_scenario, :set_cloud, :set_subnet, :set_instance]

  before_action :set_scenario, only: [:show, :edit, :update, :destroyme, :status, :boot, :unboot, :boot_status, :modify_players, :modify, :add_cloud, :add_student_group_to_players]
  
  before_action :set_cloud, only: [:boot_cloud, :unboot_cloud, :delete_cloud, :modify_cloud, :add_subnet]
  
  before_action :set_subnet, only: [:boot_subnet, :unboot_subnet, :modify_subnet, :delete_subnet, :add_instance]
  
  before_action :set_instance, only: [:boot_instance, :unboot_instance, :delete_instance, :get_instance_bash_history]

  before_action :set_group, only: [:add_player, :add_student_group, :remove_student_group]


  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = []
    if @user.is_admin?
      @scenarios = Scenario.all
    else
      @scenarios = Scenario.where(user_id: current_user.id)
    end
  end

  def status
    # @total_booted = 0
    # @total_instances = 0

    # @scenario.clouds.each do |cloud|
    #   cloud.subnets.each do |subnet|
    #     subnet.instances.each do |instance|
    #       if instance.scoring_page.blank?
    #         next
    #       end
    #       @total_instances += 1
    #       body = Net::HTTP.get(URI(instance.scoring_page))
    #       puts "GET #{instance.scoring_page}"
    #       begin
    #         if Nokogiri.XML(body).children.first.name = 'Error'
    #         end
    #       rescue NoMethodError
    #         @total_booted += 1
    #       end
    #     end
    #   end
    # end
    respond_to do |format|
      format.html
      format.json { render json: {total: @total_instances, booted: @total_booted} }
    end
  end
  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
    @templates = YmlRecord.yml_headers.map {|filename,name,desc| [name,filename,desc]}
  end

  # GET /scenarios/1/edit
  def edit
    @templates = []
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    # scrub this template input
    if template = scenario_params["template"]
      @scenario = YmlRecord.load_yml("scenarios/local/#{template}/#{template}.yml")
    else
      @scenario = Scenario.new(scenario_params)
    end

    @scenario.user_id = current_user.id
    @scenario.save!

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.json
  def destroyme
    if @scenario.booted? or @scenario.partially_booted?
      respond_to do |format|
        format.js { render 'scenarios/js/destroy_failed.js.erb', :layout => false }
      end
    else
      @scenario.destroy
      respond_to do |format|
        format.js { render js: "window.location.pathname='/scenarios'" }
        # format.js { redirect_to scenarios_url, notice: 'Scenario was successfully destroyed.' }
        # format.json { head :no_content }
      end
    end
  end

  #############################################################
  # BOOTING

  def boot
    if @scenario.stopped? or @scenario.partially_booted?
      @scenario.set_queued_boot
      @scenario.delay(queue: 'scenarios').boot(boot_dependents: true, run_asynchronously: Settings.boot_asynchronously)
      @flash_message = "Scenario #{@scenario.name} has been placed in the boot queue"
    end

    @hide_dropdown = true
    respond_to do |format|
      format.js { render 'scenarios/js/boot.js.erb', :layout => false }
    end
  end

  def unboot
    if @scenario.booted? or @scenario.partially_booted?
      @scenario.set_queued_unboot
      @scenario.delay(queue: 'scenarios').unboot(unboot_dependents: true, run_asynchronously: Settings.boot_asynchronously)
      @flash_message = "Scenario #{@scenario.name} has been placed in the unboot queue"
    end

    @hide_dropdown = true
    respond_to do |format|
      format.js { render 'scenarios/js/unboot.js.erb', :layout => false }
    end
  end

  def boot_cloud
    if @cloud.stopped?
      @cloud.set_queued_boot
      @cloud.delay(queue: 'clouds').boot
      @flash_message = "Cloud #{@cloud.name} has been placed in the boot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/boot_cloud.js.erb', layout: false }
    end
  end

  def unboot_cloud
    if @cloud.subnets_booted?
      @cloud.errors.add(:active_subnets, "Clouds subnets must be unbooted before cloud can unboot")
    else
      @cloud.set_queued_unboot
      @cloud.delay(queue: 'clouds').unboot
      @flash_message = "Cloud #{@cloud.name} has been placed in the unboot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/unboot_cloud.js.erb',  layout: false }
    end
  end

  def boot_subnet
    if not @subnet.cloud.booted?
      @subnet.errors.add(:cloudnotbooted, "Instances Subnet must be booted first")
    else
      @subnet.set_queued_boot
      @subnet.delay(queue: 'subnets').boot
      @flash_message = "Subnet #{@subnet.name} has been placed in the boot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/boot_subnet.js.erb', layout: false }
    end
  end

  def unboot_subnet
    if @subnet.instances_active?
      @subnet.errors.add(:instancesnotunbooted, "Subnets instances must be unbooted first")
    else
      @subnet.set_queued_unboot
      @subnet.delay(queue: 'subnets').unboot
      @flash_message = "Subnet #{@subnet.name} has been placed in the unboot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/unboot_subnet.js.erb', layout: false }
    end
  end

  def boot_instance
    if not @instance.subnet.booted?
      @instance.errors.add(:subnetnotbooted, "Instances Subnet must be booted first")
    else
      @instance.set_queued_boot
      @instance.delay(queue: 'instances').boot
      @flash_message = "Instance #{@instance.name} has been placed in the boot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/boot_instance.js.erb', layout: false }
    end
  end

  def unboot_instance
    if @instance.driver_id
      @instance.set_queued_unboot
      @instance.delay(queue: 'instances').unboot
      @flash_message = "Instance #{@instance.name} has been placed in the unboot queue"
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/unboot_instance.js.erb', layout: false }
    end
  end

  def boot_status
    @scenario.get_status
    respond_to do |format|
      format.js { render 'scenarios/js/boot_status.js.erb', :layout => false }
    end
  end

  ###############################################################
  #  Resource Modification

  def modify
    @scenario.name = params[:name]
    @scenario.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/modify.js.erb', layout: false }
    end
  end

  def add_cloud
    @cloud = @scenario.clouds.new
    @cloud.name = params[:name]
    @cloud.cidr_block = params[:CIDR]
    @cloud.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/add_cloud.js.erb', layout: false }
    end
  end

  def delete_cloud
    # destroy all it's parts
    if @cloud.subnets.size > 0
      @cloud.errors.add(:has_dependents, "Cannot delete cloud because it has dependents")
    else
      @cloud.destroy
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/delete_cloud.js.erb', layout: false }
    end
  end

  def modify_cloud
    @cloud.name = params[:name]
    @cloud.cidr_block = params[:CIDR]
    @cloud.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/modify_cloud.js.erb', layout: false }
    end
  end

  def add_subnet
    # should add a new subnet based on cloud
    # @subnet = Subnet.new
    # @subnet.errors.add(:name, "FOO")
    # @subnet.errors.add(:cidr_block, "FOO")

    respond_to do |format|
      format.js { render template: 'scenarios/js/add_subnet.js.erb', layout: false }
    end
  end

  def modify_subnet
    @subnet.name = params[:name]
    @subnet.cidr_block = params[:CIDR]

    if params[:internet_accessible] == "true"
      @subnet.internet_accessible = true
    else
      @subnet.internet_accessible = false
    end

    @subnet.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/modify_subnet.js.erb', layout: false }
    end
  end

  def delete_subnet
    if @subnet.instances.size > 0
      @subnet.errors.add(:has_dependents, "Cannot delete subnet because it has dependents")
    else
      @subnet.destroy
    end

    respond_to do |format|
      format.js { render template: 'scenarios/js/delete_subnet.js.erb', layout: false }
    end
  end

  def add_instance
    @instance = @subnet.instances.new(
      name: params[:name],
      ip_address: params[:ip],
      os: params[:os],
      internet_accessible: params[:internet_accessible],
      uuid: `uuidgen`.chomp
    )
    @instance.save

    respond_to do |format|

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/edit.html.haml
%h1 Editing scenario

= render 'form'

= link_to 'Show', @scenario
\|
= link_to 'Back', scenarios_path

app/views/scenarios/index.html.haml
%div.panel.panel-default

  %div.panel-heading.nav.nav-pills
    %li
      %h4
        Scenarios
    %li
      = link_to 'Load Scenario', new_scenario_path
    / %li
    /   = link_to 'Create Scenario', 'scenarios/make_scenario'
    /   = link_to 'Create Scenario', create_scenario_scenario_path(id:1)
    / %li.dropdown
    /   %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#", role: "button", "aria-expanded" => "false"}
    /     Actions
    /     %span.caret
    /   %ul.dropdown-menu{role: "menu"}
    /     %li
    /        = link_to 'create scenario'
    /        = link_to 'upload scenario'

  %div.panel-body
    %dl
    %table.table.table-bordered
      %tr
        %th Name
        %th Status
        - if @user.is_admin?
          %th Instructor
        %th

      - @scenarios.each do |scenario|
        %tr
          %td= scenario.name
          %td= scenario.status
          - if @user.is_admin?
            - if scenario.user_id
              %td= User.find(scenario.user_id).name
            - else
              %td
          %td
            %div.btn-group
              = link_to 'Show', scenario, class: 'btn btn-default'
              = link_to 'Destroy', destroyme_scenario_path(scenario), method: :post, remote: true, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/scenarios/new.html.haml
%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4#scenario-new-title
        New Scenario:
    / %li
    /   = link_to 'Default Scenarios', new_scenario_path(@scenario)
    %li
      / # = link_to 'Upload Scenario'
      / = form_tag upload_scenario_path(@scenario) do
      /   = file_field_tag :yml
      /   = submit_tag "Upload Scenario", class: 'btn'

  %div.panel-body
    - @templates.each do |template|
      %b Name:
      = template[0]
      %br
      / %span.label Description:
      %b Description:
      = template[2]
      %p
      = simple_form_for(@scenario) do |f|
        = f.hidden_field :template, :value => template[1]
        = f.button :submit, 'Create ' + template[0], class: 'btn btn-primary'
      %p
      %br

    = link_to 'Back', scenarios_path

app/views/scenarios/show.html.haml
= render '/scenarios/show/modals'

%div.panel.panel-default#scenario{data: {id: @scenario.id}}
  %div.panel-heading.nav.nav-pills
    %li
      %h4#scenario-main-title
        =@scenario.name + ":"
    %li.dropdown#action-dropdown
      %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#", role: "button", "aria-expanded" => "false"}
        Actions
        %span.caret
      %ul.dropdown-menu{role: "menu"}
        %li
          - if @scenario.stopped?
            - boot_class = ""
            - unboot_class = "hidden"
          - elsif @scenario.booting?
            - boot_class = ""
            - unboot_class = "hidden"
          - elsif (@scenario.booted? or @scenario.boot_failed?)
            - boot_class = "hidden"
            - unboot_class = ""
          - elsif @scenario.is_failed?
            - boot_class = "hidden"
            - unboot_class = ""

          = link_to 'Boot', boot_scenario_path(@scenario), method: :post, remote:true, id: 'boot-button', class: boot_class
          = link_to 'Unboot', unboot_scenario_path(@scenario), method: :post, remote:true, id: 'unboot-button', class: unboot_class

          / = link_to 'Pause'
          = link_to 'Destroy', destroyme_scenario_path(@scenario), method: :post, remote: true
          = link_to 'Show Boot Log', get_log_scenario_path(@scenario, kind: 'scenario'), method: :post, remote: true
          = link_to 'Save Changes', save_changes_scenario_path(@scenario), method: :post, remote: true

  %div.panel-body

    %div.css-treeview
      %ul
        %li
          %input{ type: 'checkbox', id: 'item-instructions', checked: 'checked'}
          %label{ for: 'item-instructions'}
            Instructions
          %ul
            = @scenario.instructions
        %p
        %li
          = render '/scenarios/show/scenario'
        %li
          = render '/scenarios/show/players'

= link_to 'Back', scenarios_path, class: 'btn btn-default'

%script
  = "get_boot_status('#{@scenario.id}');"

app/views/scenarios/status.html.haml
%h1= @scenario.name
Booted: 
= @total_booted
Total:
= @total_instances