config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds

  resources :scenarios do
    member do
      post 'destroyme'
      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'

      post 'destroy_scenario'
      post 'destroy_cloud'
      post 'destroy_subnet'
      post 'destroy_instance'

      post 'add_cloud'
      post 'add_subnet'
      post 'add_instance'

      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'delete_cloud'
      post 'delete_subnet'
      post 'delete_instance'

      post 'modify'
      post 'modify_cloud'
      post 'modify_subnet'
      post 'modify_instance'

      post 'add_player'
      post 'modify_players'
      post 'delete_player'

      post 'add_student_group'
      post 'remove_student_group'

      post 'get_log'
      post 'get_instance_bash_history'
      post 'boot_status'

      post 'upload'
      post 'save_changes'

    end
  end
  
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get 'instructor', to: 'instructor#index'

  post 'instructor/student_group_new'
  post 'instructor/student_group_assign'
  post 'instructor/student_group_delete'
  post 'instructor/student_group_remove'

  # get 'student_groups', to: 'student_groups#index'
  # post 'student_groups/new'
  # get 'student_groups/destroy'
  post 'student_groups/add_to'
  # get 'student_groups/remove_from'
  # post 'student_groups/add_to'

  get 'student', to: 'student#index'

  get 'admin', to: 'admin#index'
  post 'admin/instructor_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'

  # Insecure, needs to be rewritten
  # get 'scoring/instructor/:scenario', to: 'scoring#instructor'
  # get 'scoring/student/:scenario', to: 'scoring#student'
  # post 'scoring/answer_question/:scenario/:question', to: 'scoring#answer_question'
  # get 'scoring/instructor_student/:scenario/:user', to: 'scoring#instructor_student'
  # post 'scoring/answer_open_question'
  # get 'scoring/answer_dump'
  # get 'documentation', to: 'documentation#index'
  # get 'documentation/scenarios/:id', to: 'documentation#show'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
  before_action :authenticate_instructor

  def index
    
  end

  def student_group_new
    @user = User.find(current_user.id)

    if @user.student_groups.find_by_name(params[:name])
      redirect_to '/instructor', notice: "Student Group already exists."
    else
      student_group = @user.student_groups.new(name: params[:name])
      student_group.save
      redirect_to '/instructor', notice: "Student Group created."
    end
  end

  def student_group_assign
    params[:selects].each do |a|
      if a[1] != ''
        if !@user.student_groups.find_by_name(a[1]).student_group_users.find_by_user_id(a[0])
          sgu = @user.student_groups.find_by_name(a[1]).student_group_users.new(user_id: a[0])
          sgu.save
        end
      end
    end
    redirect_to '/instructor', notice: "Student(s) assigned to Student Group"
  end

  def student_group_remove
    StudentGroupUser.find(params[:student_group_user]).delete
    redirect_to '/instructor', notice: "Student Removed from Student Group"
  end

  def student_group_delete
    StudentGroup.find(params[:student_group_id]).delete
    redirect_to '/instructor', notice: "Student Group deleted."
  end

end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/instructor/index.html.haml
%div.modal#modal-add-cloud{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          = "Add Student"
          %span#modal-title
      %div.modal-body#modalbody
        = form_tag student_groups_add_to_path(@scenario), remote:true do 
          %div#cidr-div
            = label_tag "Name:", nil, class: 'control-label'
            = text_field_tag "name", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %p
          %div#cidr-div
            = label_tag nil, "CIDR:", class: 'control-label'
            = text_field_tag "CIDR", nil, class: 'form-control'
            %span.help-block.inline#cidr-help
          %p
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading
    %h3 Instructor Home

  %div.panel-body
    %dl
      %dt Welcome instructors. On this page you can change your account information and view your Student Groups. Don't worry about Student Groups for now, you can test the Scenarios without them. They will be completed shortly though.
      %p
      /A Student Group is a collection of users. When you launch a Scenario you can specify which student groups are on which Teams in the Scenario. This gives all students in the Student Group login credentials for the Scenario. The student can login to this site to view those credentials. If you are just testing Scenarios out for yourself you do not need to worry about creating any Student Groups for now. Click 'edit' under Student Groups to manage them.
      %p

    %h3 Getting Started:
    %dl Click on the 'SCENARIOS' button on the top of the page to create a new Scenario.
    %p
    %h3 Registration Code:
    %dl
      = @user.registration_code

    %h3 Student Groups:
    %dl
      = form_tag '/instructor/student_group_new' do
        %b.inline New Student Group:
        = text_field '', :name, :style => "width:200px;"
        = submit_tag "create"
      %p

      - @user.student_groups.each do |student_group|
        - if student_group.name == "All"
          = form_tag 'instructor/student_group_assign' do
            %b= student_group.name
            %table
              %tr
                %th Name
                %th Email
              - student_group.student_group_users.each do |student_group_user|
                %tr
                  %td= student_group_user.user.name
                  %td= student_group_user.user.email
                  %td
                    = select_tag 'selects[' + student_group_user.user.id.to_s + ']', options_for_select(@user.student_groups.pluck(:name).select{|a| a != "All"}.append(""), "") 
              %tr
                %td
                %td
            %p

        - else
          %b= student_group.name
          = link_to 'delete', instructor_student_group_delete_path(student_group_id: student_group.id)

          %table
            %tr
              %th Name
              %th Email
              %th
            - student_group.student_group_users.each do |student_group_user|
              %tr
                %td= student_group_user.user.name
                %td= student_group_user.user.email
                %td= link_to 'remove', instructor_student_group_remove_path(student_group_user: student_group_user)
        %p

      / %dl
      /   - if @student_groups.size == 0
      /     = "none"
      /   - @student_groups.each do |student_group|
      /     %dt
      /     %b Name:
      /     = student_group.name
      /     %b Size:
      /     = @student_groups_size[student_group.name]
      /   %p
      /   = link_to 'edit', student_groups_path, class: 'btn btn-primary'

    %div
      %h3 Account Information:
      %dl
        %dt
          Name:
          =@user.name
        %dt
          Email:
          =@user.email
        %dt Password: ********
        %dt
          = link_to 'edit', edit_user_registration_path, class: 'btn btn-primary'
        %dt
          Last Sign In:
          =@user.last_sign_in_at
          From:
          =@user.last_sign_in_ip